import { supabase } from "@/lib/supabase";
import type { MediaFile } from "@/types/media";

export type ServiceResponse<T = any> = {
  success: boolean;
  data?: T;
  error?: string;
};

export type UploadMediaResponse = {
  success: boolean;
  file?: MediaFile;
  error?: string;
};

export interface UploadOptions {
  bucket_name: string;
  folder?: string;
  alt_text?: string;
  caption?: string;
  category?: string;
  tags?: string[];
  uploaded_by?: string;
  is_public?: boolean;
}

/**
 * Generates a production-safe storage path for a file.
 */
export function generateFilePath(folder: string | null | undefined, filename: string): string {
  const timestamp = Date.now();
  // Remove spaces and special characters, keep periods, dashes, and underscores
  const sanitizedFilename = filename
    .replace(/[^a-zA-Z0-9.\-_]/g, "")
    .toLowerCase();
  
  const basePath = folder ? `${folder.replace(/^\/|\/$/g, "")}/` : "";
  return `${basePath}${timestamp}-${sanitizedFilename}`;
}

/**
 * Generates a public URL for a file stored in a Supabase public bucket.
 */
export function getPublicFileUrl(bucket_name: string, storage_path: string): string {
  const { data } = supabase.storage
    .from(bucket_name)
    .getPublicUrl(storage_path);
    
  return data.publicUrl;
}

/**
 * Helper to determine the media_type enum value based on mime type.
 */
function determineMediaType(mimeType: string): MediaFile['media_type'] {
  if (mimeType.startsWith("image/")) return "image";
  if (mimeType.startsWith("video/")) return "video";
  if (mimeType.startsWith("audio/")) return "audio";
  if (mimeType === "application/pdf") return "pdf";
  return "document";
}

/**
 * Uploads a file to Supabase Storage and records its metadata in the database.
 */
export async function uploadMediaFile(
  file: File,
  options: UploadOptions
): Promise<UploadMediaResponse> {
  try {
    const storage_path = generateFilePath(options.folder, file.name);
    
    // 1. Upload to Supabase Storage
    const { error: uploadError } = await supabase.storage
      .from(options.bucket_name)
      .upload(storage_path, file, {
        cacheControl: "3600",
        upsert: false,
      });

    if (uploadError) {
      console.error("[uploadMediaFile] Storage upload error:", uploadError.message);
      return { success: false, error: uploadError.message };
    }

    // 2. Generate Public URL (assuming public bucket for CMS assets)
    const file_url = getPublicFileUrl(options.bucket_name, storage_path);

    // 3. Prepare Metadata
    const file_extension = file.name.split('.').pop()?.toLowerCase() || '';
    const media_type = determineMediaType(file.type);
    
    const mediaPayload: Omit<MediaFile, 'id' | 'created_at' | 'updated_at'> = {
      file_name: `${Date.now()}-${file.name}`, // Internal unique reference
      original_name: file.name,
      file_url,
      thumbnail_url: null, // To be generated by edge functions or external services
      mime_type: file.type,
      file_size: file.size,
      file_extension,
      media_type,
      alt_text: options.alt_text || null,
      caption: options.caption || null,
      seo_title: null,
      seo_description: null,
      category: options.category || null,
      folder: options.folder || null,
      tags: options.tags || null,
      uploaded_by: options.uploaded_by || null,
      bucket_name: options.bucket_name,
      storage_path,
      is_public: options.is_public ?? true,
      width: null, // Would require client-side extraction or serverless trigger
      height: null,
      duration: null,
    };

    // 4. Insert Metadata into 'media' table
    const { data: dbData, error: dbError } = await supabase
      .from("media")
      .insert([mediaPayload])
      .select()
      .single();

    if (dbError) {
      console.error("[uploadMediaFile] Database insert error:", dbError.message);
      // Rollback storage upload if DB fails
      await supabase.storage.from(options.bucket_name).remove([storage_path]);
      return { success: false, error: dbError.message };
    }

    return { success: true, file: dbData as MediaFile };
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "An unexpected upload error occurred.";
    console.error("[uploadMediaFile] Unexpected error:", err);
    return { success: false, error: errorMessage };
  }
}

/**
 * Fetches all media files, ordered by most recently created.
 */
export async function getMediaFiles(): Promise<MediaFile[]> {
  try {
    const { data, error } = await supabase
      .from("media")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) {
      console.error("[getMediaFiles] Error fetching media files:", error.message);
      return [];
    }

    return data as MediaFile[];
  } catch (err) {
    console.error("[getMediaFiles] Unexpected error:", err);
    return [];
  }
}

/**
 * Fetches media files filtered by a specific category.
 */
export async function getMediaByCategory(category: string): Promise<MediaFile[]> {
  try {
    const { data, error } = await supabase
      .from("media")
      .select("*")
      .eq("category", category)
      .order("created_at", { ascending: false });

    if (error) {
      console.error(`[getMediaByCategory] Error fetching media for category ${category}:`, error.message);
      return [];
    }

    return data as MediaFile[];
  } catch (err) {
    console.error(`[getMediaByCategory] Unexpected error for category ${category}:`, err);
    return [];
  }
}

/**
 * Deletes a media file from both Storage and the database.
 */
export async function deleteMediaFile(
  id: string,
  bucket_name: string,
  storage_path: string
): Promise<ServiceResponse<null>> {
  try {
    // 1. Delete from Storage
    const { error: storageError } = await supabase.storage
      .from(bucket_name)
      .remove([storage_path]);

    if (storageError) {
      console.error(`[deleteMediaFile] Storage deletion error for path ${storage_path}:`, storageError.message);
      return { success: false, error: storageError.message };
    }

    // 2. Delete from Database
    const { error: dbError } = await supabase
      .from("media")
      .delete()
      .eq("id", id);

    if (dbError) {
      console.error(`[deleteMediaFile] Database deletion error for ID ${id}:`, dbError.message);
      return { success: false, error: dbError.message };
    }

    return { success: true };
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "An unexpected deletion error occurred.";
    console.error(`[deleteMediaFile] Unexpected error for ID ${id}:`, err);
    return { success: false, error: errorMessage };
  }
}

/**
 * Updates the metadata properties of a specific media file.
 */
export async function updateMediaMetadata(
  id: string,
  payload: Pick<MediaFile, 'alt_text' | 'caption' | 'category' | 'tags' | 'seo_title' | 'seo_description'>
): Promise<ServiceResponse<MediaFile>> {
  try {
    const { data, error } = await supabase
      .from("media")
      .update(payload)
      .eq("id", id)
      .select()
      .single();

    if (error) {
      console.error(`[updateMediaMetadata] Error updating metadata for ID ${id}:`, error.message);
      return { success: false, error: error.message };
    }

    return { success: true, data: data as MediaFile };
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "An unexpected update error occurred.";
    console.error(`[updateMediaMetadata] Unexpected error for ID ${id}:`, err);
    return { success: false, error: errorMessage };
  }
}

/**
 * Retrieves a list of distinct folder names used within the media library.
 * Useful for building folder-based navigation in a Media Manager UI.
 */
export async function getMediaFolders(): Promise<string[]> {
  try {
    // Note: Standard Supabase JS doesn't have a SELECT DISTINCT. 
    // We fetch non-null folders and extract unique values in memory.
    // For very large tables, a Postgres RPC (Stored Procedure) is recommended.
    const { data, error } = await supabase
      .from("media")
      .select("folder")
      .not("folder", "is", null);

    if (error) {
      console.error("[getMediaFolders] Error fetching folders:", error.message);
      return [];
    }

    const folders = data.map((item) => item.folder as string);
    const uniqueFolders = Array.from(new Set(folders));
    
    return uniqueFolders.sort();
  } catch (err) {
    console.error("[getMediaFolders] Unexpected error:", err);
    return [];
  }
}
